---
- hosts: Redhatos
  become: yes
  tasks: 
  - name: execute linux command  1
    command: hostname -f
    register: myresult
  - name: display the myresult
    debug:
      msg: "{{myresult}}"

  - name: install git 2
    yum:
      name: git
      state: present
    when: myresult.stderr ==""

  - name: install tree 3
    yum:
      name: tree
      state: present
    when: myresult.stderr !="" 


